### ISSUE TITLE
gdk_window_get_state: assertion GDK_IS_WINDOW (window) failed

### ISSUE THREAD

**Issue by hungryemon** [solsticedhiver/flarte#2]
libGL error: did not find extension DRI_Mesa version 1
libGl error: failed to load driver: iris
libGL error: did not find extension DRI_Mesa version 1
libGl error: failed to load driver: iris
libGL error: did not find extension DRI_Mesa version 1
libGl error: failed to load driver: swrast

after installing .snap file getting this error. Anyway to fix this? (Facing similar issue with one of my app) runs on development mode

**Comment by solsticedhiver** [comment]
Are you reporting this error for my app?

I don't see the error you mention above for my app on ubuntu 22.04. If it is for my app, in what distro are you running it?

I fixed a similar error, something about libGL not finding some DRI driver. And my only way to fix it was to compile myself (for the snap) a recent version of libmpv. And not used the one included in libmpv0

Take a loook at the https://github.com/solsticedhiver/flarte/blob/main/snap/snapcraft.yaml file
